# Generated by Django 4.2.4 on 2023-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
