# Generated by Django 4.2.4 on 2023-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_currency_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Processing", "Processing"),
                    ("completed", "completed"),
                    ("Failed", "Failed"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
