# Generated by Django 4.2.4 on 2023-10-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="settlement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Processing", "Processing"),
                    ("completed", "completed"),
                    ("Failed", "Failed"),
                ],
                default="Processing",
                max_length=200,
                null=True,
            ),
        ),
    ]
