# Generated by Django 4.2.4 on 2023-10-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_property_rent_duration_required_if_for_rent"),
        ("users", "0007_lister_phone_renter_phone"),
        ("payments", "0004_rename_created_payment_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_code", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "down_payment_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "interval",
                    models.SmallIntegerField(
                        choices=[(1, "Quarterly"), (2, "Binually")]
                    ),
                ),
                (
                    "invoice_limit",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Processing"), (2, "Active"), (3, "Settled")],
                        default=1,
                    ),
                ),
                (
                    "subscription_code",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("num_of_payments_made", models.SmallIntegerField(default=0)),
                ("next_payment_date", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.renter"
                    ),
                ),
                (
                    "down_payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.payment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.plan"
                    ),
                ),
            ],
        ),
    ]
