# Generated by Django 4.2.4 on 2023-10-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_plan_paymentsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
