# Generated by Django 4.2.4 on 2023-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_paymentsubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="onetime_payment_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="total_amount_at_the_end_of_sub",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
