# Generated by Django 4.2.4 on 2023-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_payment_duration_plan_onetime_payment_amt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsubscription",
            name="next_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
