# Generated by Django 4.2.4 on 2023-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_alter_paymentsubscription_next_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="interval",
            field=models.SmallIntegerField(
                choices=[(1, "Quarterly"), (2, "Bianually"), (3, "Monthly")]
            ),
        ),
    ]
