# Generated by Django 4.2.4 on 2023-11-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_alter_paymentsubscription_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsubscription",
            name="down_payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="payments.payment"
            ),
        ),
    ]
