# Generated by Django 4.2.4 on 2023-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtor",
            name="Bank_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="realtor",
            name="business_document",
            field=models.FilePathField(blank=True, null=True, path="/uploads"),
        ),
        migrations.AddField(
            model_name="renter",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
