# Generated by Django 4.2.4 on 2023-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_realtor_bank_details_realtor_business_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="business_document",
            field=models.FilePathField(blank=True, null=True, path="uploads/"),
        ),
    ]
