# Generated by Django 4.2.4 on 2023-10-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_realtor_business_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="business_document",
            field=models.FilePathField(
                blank=True, null=True, path="media/uploads/documents"
            ),
        ),
    ]
