# Generated by Django 4.2.4 on 2023-10-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0007_remove_property_realtor"),
        ("users", "0004_alter_realtor_business_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("Bank_details", models.TextField(blank=True, null=True)),
                (
                    "business_document",
                    models.FilePathField(
                        blank=True, null=True, path="media/uploads/documents"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("owner", "Owner"), ("agent", "Agent")],
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Realtor",
        ),
    ]
