# Generated by Django 4.2.4 on 2023-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_lister_phone_renter_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lister",
            name="business_document",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/documents"
            ),
        ),
    ]
