# Generated by Django 4.2.4 on 2023-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settlement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settled",
            options={"verbose_name_plural": "settled"},
        ),
    ]
