# Generated by Django 4.2.4 on 2023-08-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("1B", "1 Bedroom"),
                            ("2B", "2 Bedroom"),
                            ("CA", "Commercial Apartment"),
                            ("MT", "Commercial Apartment"),
                            ("4S", "For Sale"),
                            ("4R", "For Rent"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.realtor"
                    ),
                ),
            ],
        ),
    ]
