# Generated by Django 4.2.4 on 2023-08-04 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.TextField(blank=True, null=True)),
                ("Region", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("suburb", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1B", "1 Bedroom"),
                            ("2B", "2 Bedroom"),
                            ("CA", "Commercial Apartment"),
                            ("MT", "Commercial Apartment"),
                            ("4S", "For Sale"),
                            ("4R", "For Rent"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="location",
        ),
        migrations.RemoveField(
            model_name="property",
            name="property_type",
        ),
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[("$", "$"), ("GHS", "GHS")], max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="location_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.ImageField(upload_to="uploads/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="Location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.location",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.propertytype",
            ),
        ),
    ]
