# Generated by Django 4.2.4 on 2023-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_location_propertytype_remove_property_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
