# Generated by Django 4.2.4 on 2023-08-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_property_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="Location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.location",
            ),
        ),
        migrations.AlterField(
            model_name="propertytype",
            name="type",
            field=models.CharField(
                choices=[
                    ("1B", "1 Bedroom"),
                    ("2B", "2 Bedroom"),
                    ("CA", "Commercial Apartment"),
                    ("MT", "Mortgage Apartment"),
                    ("4S", "For Sale"),
                    ("4R", "For Rent"),
                ],
                max_length=200,
            ),
        ),
    ]
