# Generated by Django 4.2.4 on 2023-08-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_property_location_alter_propertytype_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
