# Generated by Django 4.2.4 on 2023-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_property_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
    ]
