# Generated by Django 4.2.4 on 2023-10-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0007_remove_property_realtor"),
        ("users", "0005_lister_delete_realtor"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="lister",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lister",
            ),
        ),
    ]
