# Generated by Django 4.2.4 on 2023-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_property_lister"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="for_rent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="rent_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("for_rent", True), ("rent_duration__isnull", False)),
                    models.Q(("for_rent", False), ("rent_duration__isnull", True)),
                    _connector="OR",
                ),
                name="rent_duration_required_if_for_rent",
            ),
        ),
    ]
