# Generated by Django 4.2.4 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0012_alter_propertyimage_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="max_rent_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="min_rent_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
