# Generated by Django 4.2.4 on 2023-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0013_alter_property_max_rent_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("GHS", "GHS")], max_length=200, null=True
            ),
        ),
    ]
