# Generated by Django 4.2.4 on 2023-10-30 13:08

from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_alter_property_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_images",
                to="property.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="upload",
            field=models.ImageField(
                blank=True, upload_to=property.models.get_property_images_upload_path
            ),
        ),
    ]
