# Generated by Django 4.2.4 on 2023-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0016_alter_property_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertytype",
            name="type",
            field=models.CharField(
                choices=[
                    ("1B", "1 Bedroom House"),
                    ("2B", "2 Bedroom House"),
                    ("3B", "3 Bedroom House"),
                    ("CA", "Commercial Apartment"),
                    ("MT", "Mortgage Apartment"),
                    ("1BSC", "1 Bedroom Self-Contained"),
                    ("2BSC", "2 Bedroom Self-Contained"),
                ],
                max_length=200,
            ),
        ),
    ]
